[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "https://vakac995.github.io"

[env]
PORT = "8000"
